lims:
  projectFileStructure:
    groovyQueriesDir: src/main/groovy
    groovyOperationsDir: src/main/groovy
    groovyExtendersDir: src/main/groovy
  features:
  #- beSqlQueries
  - eventDbLogging
  #- compiledGroovy
  l10n: [en,ru]
  modules:
  - core:
      entities:
      - users
      - _logout_
  application:
  - _welcome_
  - _dictionaries_
  - _api_
  - attachments
  - attributes
  - attribute_groups
  - attribute_sources
  - attribute_types
  - analyses
  - databases
  - devices
  - device_types
  - device_statuses
  - programs
  - projects
  - runs
  - run_samples
  - run_metrics
  - run_applications
  - reports
  - samples
  - sequencing_data
  - sample_templates
  - workflows
  - uploads
  - nf_workflows
  - nf_heartbeat
  scripts:
  - Post-db
  - dictionaries
  - test-hematology/users
  - test-hematology/project
  - test-hematology/systemsettings
  - test-hematology/analyses
  - test-hematology/devices
  - test-hematology/sample_templates
  - test-hematology/workflows
  - test-hematology/test_data
  - attributes/types
  includes: common
