version: "3"
services:
  postgres:
    image: postgres:14
    container_name: postgres-lims
    networks:
      - sequencerhub
    expose:
      - 5435
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=lims
      - POSTGRES_USER=lims
      - POSTGRES_DB=lims
    restart: unless-stopped
    volumes:
      - /servers/lims/empty.sql:/docker-entrypoint-initdb.d/init.sql
      - /hs_drive/postgres-lims/postgres:/var/lib/postgresql/data
  postgres-dev:
    image: postgres:14
    container_name: postgres-dev-lims
    networks:
      - sequencerhub
    expose:
      - 5436
    ports:
      - 5436:5432
    environment:
      - POSTGRES_PASSWORD=lims
      - POSTGRES_USER=lims
      - POSTGRES_DB=lims
    restart: unless-stopped
    volumes:
      - /servers/lims/empty.sql:/docker-entrypoint-initdb.d/init.sql
      - /hs_drive/postgres-lims/postgres-dev:/var/lib/postgresql/data
  lims:
    image: tomcat:7-jdk8-openjdk
    container_name: lims
    networks:
      - sequencerhub
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - CATALINA_OPTS=-Djava.security.egd=file:/dev/./urandom
      #- CATALINA_OPTS=-Djava.security.egd=file:/dev/./urandom -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8106
#    expose:
#      - 9090
#    ports:
#      - 9090:8080
      #- 127.0.0.1:9106:8106
    volumes:
      - /servers/lims/docker.out/logs:/usr/local/tomcat/logs
      - /servers/lims/docker.out/sessions:/sessions
      - /servers/lims/docker.in/lims.war:/usr/local/tomcat/webapps/ROOT.war
      - /servers/lims/docker.in/postgresql-42.2.6.jar:/usr/local/tomcat/lib/postgresql-42.2.6.jar
      - /servers/lims/docker.in/src:/hotreload/src
      - /servers/lims/docker.in/project.yaml:/hotreload/project.yaml

networks:
  sequencerhub:
    name: sequencerhub_default
    external: true